openapi: 3.1.0
info:
  version: 1.0.0
  title: Task Pro
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Task Pro
tags:
  - name: Auth
    description: Auth Endpoint.
  - name: Board
    description: Board Endpoint.
  - name: Task
    description: Task Endpoint.
  - name: Column
    description: Column Endpoint.
servers:
  - url: http://localhost:3000
    description: Local Server
  - url: https://taskpro-backend-yofv.onrender.com
    description: Production Server
paths:
  /auth/login:
    post:
      # - bearerAuth: []
      $ref: ../swagger/paths/auth/login.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml
  /auth/logout-others:
    post:
      $ref: ../swagger/paths/auth/logoutOthers.yaml
  # Board Paths
  /board:
    get:
      $ref: ../swagger/paths/board/getBoards.yaml
    post:
      $ref: ../swagger/paths/board/addBoard.yaml
  /board/{board_id}:
    delete:
      $ref: ../swagger/paths/board/deleteBoard.yaml
  # Tasks Paths
  /tasks:
    post:
      $ref: ../swagger/paths/task/addTask.yaml
  /tasks/{board_id}:
    get:
      $ref: ../swagger/paths/task/getTasksByBoardId.yaml
  /tasks/{task_id}:
    delete:
      $ref: ../swagger/paths/task/deleteTaskByBoardIdAndTaskId.yaml
  /tasks/{task_id}/move:
    patch:
      $ref: ../swagger/paths/task/moveTaskByBoardIdAndTaskId.yaml
  # Columns Paths
  /column:
    post:
      $ref: ../swagger/paths/column/addColumn.yaml
  /column/{board_id}:
    get:
      $ref: ../swagger/paths/column/getColumnsByBoardId.yaml
  /column/{column_id}:
    delete:
      $ref: ../swagger/paths/column/deleteColumnById.yaml
    patch:
      $ref: ../swagger/paths/column/updateColumnById.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
