openapi: 3.1.0
info:
  version: 1.0.0
  title: Task Pro
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Task Pro
tags:
  - name: Auth
    description: Auth operations.
  - name: Board
    description: Board operations.
  - name: Task
    description: Task operations.
servers:
  - url: http://localhost:3000
    description: Local Server
  - url: https://taskpro-backend-yofv.onrender.com
    description: Production Server
paths:
  /auth/login:
    post:
      # - bearerAuth: []
      $ref: ../swagger/paths/auth/login.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml
  /auth/logout-others:
    post:
      $ref: ../swagger/paths/auth/logoutOthers.yaml
  # Board Paths
  /board:
    get:
      $ref: ../swagger/paths/board/getBoards.yaml
    post:
      $ref: ../swagger/paths/board/addBoard.yaml
  /board/{board_id}:
    delete:
      $ref: ../swagger/paths/board/deleteBoard.yaml
  # Tasks Paths
  /tasks/{board_id}:
    post: 
      $ref: ../swagger/paths/task/addTaskByBoardId.yaml
    get:
      $ref: ../swagger/paths/task/GetTasksByBoardId.yaml
  /tasks/{board_id}/{task_id}:
    delete:
      $ref: ../swagger/paths/task/DeleteTaskByBoardIdAndTaskId.yaml
  /tasks/{board_id}/{task_id}/move:
    patch: 
      $ref: ../swagger/paths/task/MoveTaskByBoardIdAndTaskId.yaml
    
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
